theme = "yesmydark"
[keys.normal]
C-c = ":q"
C-s = ":w"
C-y = "save_selection"
'#' = "toggle_comments"
A-h = "extend_to_line_start"
A-l = "extend_to_line_end"
A-x = "extend_line_above"
[keys.select]
C-c = ":q"
C-s = ":w"
C-y = "save_selection"
'#' = "toggle_comments"
A-h = "extend_to_line_start"
A-l = "extend_to_line_end"
A-x = "extend_line_above"
[editor]
auto-info = false
auto-pairs = false
auto-format = false
line-number = "relative"
bufferline = "multiple"
[editor.lsp]
auto-signature-help = false
[editor.cursor-shape]
insert = "bar"
select = "underline"
[editor.file-picker]
max-depth = 4
hidden = false
# [editor.indent-guides]
# render = true
# [editor.whitespace.render]
# space = "all"
# tab = "all"
