theme = "onedark"
[keys.normal]
C-c = ":q"
C-s = ":w"
A-c = ":bc"
C-y = "save_selection"
'#' = "toggle_comments"
[editor]
auto-info = false
auto-pairs = false
auto-format = false
[editor.whitespace.render]
#space = "all"
#tab = "all"
