theme = "autumn"
[keys.normal]
C-c = ":q"
C-s = ":w"
A-c = ":bc"
C-y = "save_selection"
'#' = "toggle_comments"
A-h = "extend_to_line_start"
A-l = "extend_to_line_end"
[editor]
auto-info = false
auto-pairs = false
auto-format = false
[editor.cursor-shape]
insert = "bar"
[editor.whitespace.render]
#space = "all"
#tab = "all"
